// Code generated by enumgen. DO NOT EDIT.
// version: {{.Version}}

import { Dict } from './dictDef';

export enum DictType {
{{- range $typeName, $e := .Enums}}
    {{$typeName}} = '{{styleName $.TypeStyle $typeName}}', // {{if $e.Description}}{{$e.Description}}: {{end}}{{$e.Explain}}
{{- end}}
}

export const ENUMS = {
    {{- range $typeName, $e := .Enums}}
    {{$typeName}}: {
    {{- range $ee := .Oneof}}
        {{ formatName $ee.Name}}: {{$ee.RawValue}}, // {{$ee.Label}}
    {{- end}}
    } as const,
    {{- end}}
} as const;

export const Enums = {
{{- range $typeName, $e := .Enums}}
{{- if $e.Description}}
    // {{$e.Description}}
{{- end}}
    {{$typeName}}: new Dict('{{styleName $.TypeStyle $typeName}}', [
    {{- range $ee := .Oneof}}
        { value: {{ printf "ENUMS.%s.%s" $typeName (formatName $ee.Name) }}, label: '{{$ee.Label}}' }, // {{$ee.RawValue}}: {{$ee.Label}}
    {{- end}}
    ]),
{{- end}}
}
