// Code generated by enumgen. DO NOT EDIT.
// version: {{.Version}}
{{- if .IsDeprecated}}
//
// Deprecated: this is a deprecated file.
{{- end}}
package {{.Package}}

import (
	"cmp"
	"slices"
{{- if .HasContainInteger}}
	"strconv"
{{- end}}
)

{{- range $typeName, $e := .Enums}}
{{- if $e.Description}}
// {{$e.Description}}
{{- end}}
var __{{$typeName}}_Enum_Validity = []{{$typeName}} { 
{{- range $ee := .Oneof}}
	{{$ee.GoName}}, // {{$ee.RawValue}}: {{$ee.Label}}
{{- end}}
}

// Value returns the original type value.
// {{if $e.Description}}{{$e.Description}}: {{end}}{{$e.Explain}}
func (x {{$typeName}}) Value() {{$e.Format}} {
    return {{$e.Format}}(x)
}

// ValueString returns the original type value as string.
// {{if $e.Description}}{{$e.Description}}: {{end}}{{$e.Explain}}
func (x {{$typeName}}) ValueString() string {
    return {{if eq $e.Type "string" }} x.Value() {{else}} strconv.FormatInt(int64(x), 10) {{end}}
}

// EnumCount the number of enum values.
func ({{$typeName}}) EnumCount() int {
	return {{len .Oneof}}
}

// IsZeroValue returns the enum value is valid or not.
func (x {{$typeName}}) IsZeroValue() bool {
	var zero {{$typeName}}
    return x == zero
}

// IsValid whether the enum value is valid or not.
func (x {{$typeName}}) IsValid() bool {
	return slices.Contains(__{{$typeName}}_Enum_Validity, x)
}

// Label returns the enum value's label.
// {{if $e.Description}}{{$e.Description}}: {{end}}{{$e.Explain}}
func (x {{$typeName}}) Label(dflt ...string) (s string) {
	switch x {
	{{- range $ee := .Oneof}}
		case {{$ee.GoName}}: // {{$ee.RawValue}}
			s = "{{$ee.Label}}"
	{{- end}}
		default:
			s = cmp.Or(dflt...)
	}
	return s
}

// ParseLabel parse label to the enum value
// {{if $e.Description}}{{$e.Description}}: {{end}}{{$e.Explain}}
func (x *{{$typeName}}) ParseLabel(s string, dflt ...{{$typeName}}) {
	switch s {
	{{- range $ee := .Oneof}}
		case "{{$ee.Label}}": // {{$ee.RawValue}}
			*x = {{$ee.GoName}}
	{{- end}}
		default:
			*x = cmp.Or(dflt...)
	}
}
{{- end}}
