// Code generated by errgen. DO NOT EDIT.
// version: {{.Version}}
{{- if .IsDeprecated}}
//
// Deprecated: this is a deprecated file.
{{- end}}
package {{.Package}}

import (
	errors "{{.Epk}}"
)
{{- range $e := .Enums}}

{{- range $ee := $e.Values}}
// Err{{$ee.OriginalName}} {{$ee.Value}}: {{.Label}}
func Err{{$ee.OriginalName}}() *errors.Error {
{{- if eq .Mode "errorx" }} 
	return errors.New(int32({{$ee.OriginalName}}), {{$ee.OriginalName}}.String())
{{- else }}
	return errors.New(int32({{$ee.OriginalName}}), {{$ee.OriginalName}}.String(), {{$ee.OriginalName}}.String())
{{- end}}
}
{{- end}}

{{- end}}